export const categories = [
  "Food",
  "Shopping",
  "Travel",
  "Entertainment",
  "Utilities",
  "Health",
  "Transport",
  "Housing",
  "Education",
  "Investments",
  "Miscellaneous",
];

export const subCategories = {
  Food: [
    "Breakfast",
    "Lunch",
    "Dinner",
    "Snacks",
    "Drinks",
    "Desserts",
    "Groceries",
  ],
  Shopping: [
    "Clothing",
    "Electronics",
    "Home Decor",
    "Books",
    "Beauty & Personal Care",
    "Sports & Outdoor",
    "Kids & Babies",
  ],
  Travel: ["Flights", "Hotels", "Tours", "Transportation", "Entertainment"],
  Entertainment: [
    "Movies",
    "Concerts",
    "Theater",
    "Museums",
    "Subscription Services",
    "Sports Events",
  ],
  Utilities: [
    "Electricity",
    "Water",
    "Internet",
    "Mobile Phone",
    "Cable & Satellite TV",
  ],
  Health: [
    "Haircut",
    "Doctor Visits",
    "Medication",
    "Therapies",
    "Dental Care",
    "Eye Care",
    "Gym & Fitness",
  ],
  Transport: [
    "Public Transport",
    "Taxis & Rideshares",
    "Fuel",
    "Vehicle Maintenance",
    "Parking",
  ],
  Housing: ["Rent", "Mortgage", "Maintenance", "Furniture", "Home Improvement"],
  Education: [
    "Tuition",
    "Books & Materials",
    "Courses & Workshops",
    "Online Learning",
    "Stationery",
  ],
  Investments: [
    "Stocks",
    "Bonds",
    "Real Estate",
    "Mutual Funds",
    "Retirement Savings",
    "Cryptocurrency",
  ],
  Miscellaneous: ["Gifts", "Donations", "Personal Care", "Hobbies", "Other"],
};

export const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const cards = {
  Zach: ["PayNow", "UOB", "Citibank", "OCBC"],
  Faith: ["PayNow", "UOB", "HSBC"],
};
